finder/urls.py
from django.urls import path, re_path
from . import views

app_name = 'finder'
urlpatterns = [
    re_path(r'^search/$', views.search, name='search'),
    path('<int:product_id>/', views.detail, name='detail'),
    path('substitute/<int:product_id>/', views.substitute, name='substitute'),
    path('saved/<int:product_id>/<int:sub_product_id>', views.save, name='save'),
]

pur_beurre/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from finder import views
from register import views as v

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('finder/', include('finder.urls')),
    path('register/', v.register, name="register"),
    path('', include('django.contrib.auth.urls')),
    path('register/', include('register.urls')),
    path('mentions', views.mentions, name='mentions') 
]

register/urls.py
from django.urls import path, re_path
from . import views

app_name = 'register'
urlpatterns = [
    path('<int:user_id>/', views.account, name='account'),
    ]

finder/models.py
from django.db import models
from django.contrib.auth.models import User


class Product(models.Model):
    name = models.CharField(max_length=2000)    
    brand = models.CharField(max_length=2000)
    nutrition_grade = models.CharField(max_length=10)
    picture = models.URLField(max_length=2000)
    off_id = models.BigIntegerField()
    categories = models.TextField(max_length=5000)
    fat = models.FloatField(max_length=100)
    satured_fat = models.FloatField(max_length=100)
    sugars = models.FloatField(max_length=100)
    salt = models.FloatField(max_length=100)
    real_name = models.CharField(max_length=2000)
    real_brand = models.CharField(max_length=2000)


class SavedProduct(models.Model):
    username = models.ForeignKey(User, on_delete=models.CASCADE)
    sub_product = models.ForeignKey(Product, related_name='savedproducts', on_delete=models.CASCADE, null=True)
    original_product = models.ForeignKey(Product, related_name='original_products', on_delete=models.CASCADE, null=True)

register/models.py
from django.db import models

# Create your models here.

finder/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader
from .models import Product, SavedProduct
from .management.commands.populate_db import strip_accents
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
import re
from django.shortcuts import redirect
stopwords = ['le', 'la', 'les', 'en', 'a', 'au', 'aux', 'd', 'des', 'et', 'de']


def index(request):
    # redirect to the main page
    template = loader.get_template('finder/main_page.html')
    return HttpResponse(template.render(request=request))


def mentions(request):
    # redirect to the 'mentions légales' page
    template = loader.get_template('finder/mentions.html')
    return HttpResponse(template.render(request=request))


def search(request):
    # process the input from the user
    # input format : str
    # return a list of str
    query = request.GET.get('query')
    query_lower = query.lower()
    list_name = re.split("[- ’? ; , ' . : ' ' " " ]", query_lower)
    stripped_query = [strip_accents(x) for x in list_name]
    clean_query = [word for word in stripped_query if word not in stopwords]

    #compare the list of str to 'name' & 'brand' of every product in Product
    # if every str of the list matches saves the product in match_list[]
    # returns a list of int
    match_list = []
    for x in Product.objects.all():
        match = 0
        for y in clean_query:
            if y in x.name or y in x.brand:
                match += 1
                if match == len(clean_query):
                    match_list.append(x.id)
            else:
                pass

    if not query:
        products_list = Product.objects.all()
    else:
        products_list = Product.objects.filter(id__in=match_list)

    title = "Choissisez le produit qui correspond à votre demande: "

    # paginate the result
    paginator = Paginator(products_list, 9)
    page = request.GET.get('page', 1)

    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        products = paginator.page(1)
    except EmptyPage:
        products = paginator.page(paginator.num_pages)

    context = {
        'products': products,
        'title': title,
        'paginate': True,
        'query': query
    }
    # render the result to search.html
    return render(request, 'finder/search.html', context)


def detail(request, product_id):
    # redirect to the details page of a product    
    product = Product.objects.get(pk=product_id)
    return render(request, 'finder/detail.html', {'product': product})


def substitute(request, product_id):
    # find food substitute for the selected product
    product = Product.objects.get(pk=product_id)
    product_categories = eval(product.categories)
    match_list = []

    # compares the starting 4 categories of the product with those of the other products in the database
    # returns a list of matching products in descending order from their 'nutrition-grade'
    for x in Product.objects.all():
        if x.id != product_id:
            match = 0
            for y in product_categories[0:4]:
                print(y)
                if y not in eval(x.categories):
                    break
                elif y in eval(x.categories):
                    match += 1
                    if match == 4:
                        match_list.append(x.id)

    substitute_product = Product.objects.filter(id__in=match_list).order_by('nutrition_grade')

    # paginate the result
    paginator = Paginator(substitute_product, 9)
    page = request.GET.get('page', 1)

    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        products = paginator.page(1)
    except EmptyPage:
        products = paginator.page(paginator.num_pages)

    context = {
        'products': products,
        'product': product,
    }

    return render(request, 'finder/substitute.html', context)


def save(request, product_id, sub_product_id):
    #  saves the selected product and its substitute into a database
    sub_product = Product.objects.get(pk=sub_product_id)
    original_product = Product.objects.get(pk=product_id)
    user = request.user
    previous_page = request.META['HTTP_REFERER']
    p = SavedProduct(username=user, sub_product=sub_product, original_product=original_product)
    p.save()

    response = redirect(previous_page)
    return response

register/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login, authenticate
from django.http import HttpResponse
from finder.models import Product, SavedProduct
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage


def register(response):
    # function for the user registration
    if response.method == 'POST':
        form = UserCreationForm(response.POST)
        if form.is_valid():
            form.save()
            return redirect("/login/")
        else:
            return redirect("register")
    else:
        form = UserCreationForm()

    return render(response, 'register/register.html', {'form': form})


def account(request, user_id):
    # redirects to the user saved products
    sub_list = SavedProduct.objects.filter(username=user_id)
    paginator = Paginator(sub_list, 5)
    page_number = request.GET.get('page')
    saved_list = paginator.get_page(page_number) 

    context = {
        'paginate': True,
        'saved_list': saved_list,
    }
    return render(request, 'account/account.html', context)

finder/templates/finder/base.html
{%load static%}
<!DOCTYPE html>
<html lang="en">

<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'finder/css/style.css' %}">
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <title>Pur Beurre Toto</title>
    <script src="https://use.fontawesome.com/releases/v5.12.1/js/all.js" crossorigin="anonymous"></script>
    <link href="http://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Scope+One" rel="stylesheet" type="text/css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/magnific-popup.min.css"
        rel="stylesheet" />
    <script src="{% static 'finder/js/scripts.js' %}"></script>
    <link rel="shortcut icon" type="image/png" href="{% static 'finder/img/pur_beurre_favicon.png' %}" />

</head>

<body id="page-top">
    <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
        <div class="container">
            <a class="navbar-brand" href="/"> <img src="{% static 'finder/img/logo_pur_beurre.png' %}"
                    style="width:40px;"> Pur beurre</a><button class="navbar-toggler navbar-toggler-right" type="button"
                data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive"
                aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto my-2 px-2">
                    <form class="form-inline px-2" action="/finder/search" method="get" autocomplete="off">
                        <input class="form-control mr-sm-2" name="query" type="text" placeholder="">
                        <button class="btn" type="submit">Chercher</button>
                    </form>
                    {% block nav-style %}{% endblock %}
                    {% if user.is_authenticated %}
                    <li class="nav-item px-3"><a href="{% url 'register:account' user.id %}" class='btn-top'
                            role="button"><i class="top fas fa-carrot"></i></a></li>
                    <li class="nav-item px-3"><a href="/logout" class='btn-top' role="button"><i
                                class="top fas fa-sign-out-alt"></i></a></li>
                    {% else %}
                    <li class="nav-item px-3"><a href="/login" class='btn-top' role="button"><i
                                class="top fas fa-user"></i></a></li>
                    {% endif %}

                </ul>
            </div>
        </div>
    </nav>

    {% block content %}

    {% endblock %}

    </div>
    <div>
        <footer class="bg-light py-3">
            <div class="d-flex flex-row justify-content-center" style="overflow:auto">
                <div class="small text-center text-muted mr-5"><a href="/mentions">Mentions légales</a></div>
                <div class="small text-center text-muted"><a href="/#bottom">Contact</a></div>
            </div>
        </footer>
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/jquery.magnific-popup.min.js"></script>
    <script src="{% static 'finder/js/scripts.js' %}"></script>
    {% block javascript %}
    {% endblock javascript %}
</body>

</html>

finder/templates/finder/detail.html
{% extends 'finder/base.html' %}

{% block content %}
<div>
    <header class="nav_masthead" style="overflow: auto;">

        <div class="col-lg-12">
            <hr>
            <h2 class="intro-text text-center" style="color: beige;">{{product.real_name}}<br>
                <hr class="divider1 my-1" />{{product.real_brand}}</h2>
            <hr>
        </div>
    </header>
    <div>

        <div class="container-fluid h-100" style="background-color: #E8A75D;">

            <div class="text-center">
                <img class="mt-5 img-thumbnail " src="{{ product.picture }}">
            </div>

            <div class="text-center pt-5 pb-3">
                <a class="btn p-2 rounded" href="{% url 'finder:substitute' product.id %}">Cherchez un subsitut à ce
                    produit</a>
            </div>

            <div class="row">
                <div class="col-lg-6 ml-auto text-center mt-5">
                    <img src="/static/finder/img/nutriscore-{{ product.nutrition_grade}}.svg"
                        alt="Note nutritionnelle NutriScore : E" style="margin-bottom:1rem;max-width:100%"><br>
                </div>
                <div class="col-lg-6 ml-auto mt-5">
                    <h4>Repères nutritionnels pour 100 g en quantité modérée </h4>

                    {% if product.fat < 3 %}
                    <img src="/static/finder/img/low.svg" class="nutrition">{{product.fat}} <b>Matières grasses /
                        Lipides</b> en faible quantité<br>
                    {% elif product.fat >= 3 and product.fat <= 20 %}
                    <img src="/static/finder/img/moderate.svg" class="nutrition">{{product.fat}} <b>Matières grasses /
                        Lipides</b> en quantité modérée<br>
                    {% else %}
                    <img src="/static/finder/img/high.svg" class="nutrition">{{product.fat}} <b>Matières grasses /
                        Lipides</b> en quantité élevée<br>
                    {% endif %}

                    {% if product.satured_fat <= 1.5 %}
                    <img src="/static/finder/img/low.svg" class="nutrition">{{product.satured_fat}} <b>Acides gras
                        saturés</b> en faible quantité<br>
                    {% elif product.satured_fat > 1.5 and product.satured_fat <= 5 %}
                    <img src="/static/finder/img/moderate.svg" class="nutrition">{{product.satured_fat}} <b>Acides gras
                        saturés</b> en quantité modérée<br>
                    {% else %}
                    <img src="/static/finder/img/high.svg" class="nutrition">{{product.satured_fat}} <b>Acides gras
                        saturés</b> en quantité élevée<br>
                    {% endif %}

                    {% if product.sugars <= 5 %}
                    <img src="/static/finder/img/low.svg" class="nutrition">{{product.sugars}} <b>Sucres</b> en faible
                    quantité<br>
                    {% elif product.sugars > 5 and product.sugars <= 12.5 %}
                    <img src="/static/finder/img/moderate.svg" class="nutrition">{{product.sugars}} <b>Sucres</b> en
                    quantité modérée<br>
                    {% else %}
                    <img src="/static/finder/img/high.svg" class="nutrition">{{product.sugars}} <b>Sucres</b> en
                    quantité élevée<br>
                    {% endif %}

                    {% if product.salt <= 0.3 %}
                    <img src="/static/finder/img/low.svg" class="nutrition">{{product.salt}} <b>Sel</b> en faible
                    quantité<br>
                    {% elif product.salt > 0.3 and product.salt <= 1.5 %}
                    <img src="/static/finder/img/moderate.svg" class="nutrition">{{product.salt}} <b>Sel</b> en quantité
                    modérée<br>
                    {% else %}
                    <img src="/static/finder/img/high.svg" class="nutrition">{{product.salt}} <b>Sel</b> en quantité
                    élevée<br>
                    {% endif %}

                </div>
            </div>
        </div>
        <div class="text-center pt-5 pb-3" style="background-color: #E8A75D;">
            <a class="btn p-2 rounded" href="https://fr.openfoodfacts.org/produit/{{ product.off_id}}"
                target="new">Consultez la fiche du produit sur OpenFoodFacts.fr</a>
        </div>



        {% endblock %}

finder/templates/finder/main_page.html
{% extends 'finder/base.html' %}

{% block content %}

<header class="masthead">
    <div class="container h-100">
        <div class="row h-100 align-items-center justify-content-center text-center">
            <div class="col-lg-10 align-self-end">
                <h1 class="text-uppercase text-white font-weight-bold">Du gras, oui, mais de qualité! </h1>
                <hr class="divider1 my-4" />
            </div>
            <div class="col-lg-8 align-self-baseline">
                <p class="text-white-75 font-weight-light mb-5">Trouvez un produit de substitution pour ceux que vous
                    consommez tous les jours.</p>
                <form class="form-inline px-2 justify-content-center" action="/finder/search" autocomplete="off">
                    <input class="form-control mr-sm-2" type="text" name="query" placeholder="">
                    <button class="btn" type="submit">Chercher</button>
                </form>
            </div>
        </div>
    </div>
</header>

<div class="container-fluid align-items-center justify-content-center pb-5" id="story">
    <div class="pt-5">
        <h2 class=" text-white font-weight-bold text-center">Colette et Rémy</h2>
        <hr class="divider2 my-4" />
    </div>
    <div class="container mb-4 text-center" style="width: 70%;">
        <p class="text-white">Pur Beurre est l'initiative de deux amoureux de la gastronomie française, Colette Tatou et
            Rémy, que vous avez déjà certainement rencontrés dans notre excellent restaurant Ratatouille.</p>
    </div>
    <div class="row">
        <div class="col-lg-4 ml-auto text-center">
            <img class="mb-3" src="/static/finder/img/portrait_colette_vintage.png" alt="colette" width="180">
        </div>
        <div class="col-lg-4 mr-auto text-center">
            <img class="" src="/static/finder/img/portrait_remy_vintage.png" alt="remy" width="180">
        </div>
    </div>
</div>
<section class="page-section" id="contact">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-8 text-center mt-2">
                <hr>
                <h2 class="mt-0">Contactez nous!</h2>
                <hr class="divider1 my-4" />
            </div>
        </div>
        <a name="bottom"></a>
        <div class="row">
            <div class="col-lg-4 ml-auto text-center mb-5 mb-lg-0">
                <i class="fas fa-phone fa-3x mb-3 text-muted"></i>
                <div id="contactInfo">07.84.95.07.24</div>
            </div>
            <div class="col-lg-4 mr-auto text-center">
                <i class="fas fa-envelope fa-3x mb-3 text-muted"></i>
                <a class="d-block" id="contactInfo" href="mailto:totobriac@gmail.com">totobriac@gmail.com</a>
            </div>
        </div>
    </div>
</section>
</div>
</header>
{% endblock %}

finder/templates/finder/mentions.html
{% extends 'finder/base.html' %}

{% block content %}

<header class="masthead">

    <div class="col-lg-12">
        <hr>
        <h2 class="intro-text text-center" style="color: beige;">Mentions légales</h2>
        <hr class="divider1 my-4" />
        <hr>
        <hr>
    </div>


    <div class="container my-auto col-lg-4">
        <div class="row" style="background-color: rgba(255, 255, 255, 0.5);">
            <div class="mx-auto pt-3">
                <hr>
                <h3>Powered by: <a href="https://www.djangoproject.com/" target="_blank">Django</a></h6>
                    <hr>
                    <h3>Deployed on: <a href="https://www.heroku.com/" target="_blank">Heroku</a></h6>
                        <hr>
                        <h3>Bootstrap template: <a href="https://blackrockdigital.github.io/startbootstrap-creative/"
                                target="_blank">Start Bootstrap</a></h6>
                            <hr>
                            <h3>Logo: <a
                                    href="https://company-82435.frontify.com/d/6Yy9WFJdtp8j/pur-beurre-style-guide#/elements-basiques/marque-et-logo"
                                    target="_blank">Pur-Beurre Openclassrooms</a></h6>
                                <hr>
                                <h3>Main page photo: <a href="https://unsplash.com/photos/k60JspcBwKE"
                                        target="_blank">Kawin Harasai</a></h6>
                                    <hr>
                                    <h3>Data: <a href="https://www.fr.openfoodfacts.com" target="_blank">Open Food
                                            Facts</a></h6>
                                        <hr>
                                        <h3>Super Héro: <a href="https://fr.wikipedia.org/wiki/L%C3%A9guman"
                                                target="_blank">Léguman</a></h6>
                                            <hr>
            </div>
        </div>
    </div>




</header>


{% endblock %}

finder/templates/finder/search.html
{% extends 'finder/base.html' %}

{% block content %}
<div>
  <header class="nav_masthead" style="overflow: auto;">
    <div class="col-lg-12">
      <hr>
      <h2 class="intro-text text-center" style="color: beige;">{{ title }}
        <hr class="divider1 my-4" />
      </h2>
      <hr>
    </div>
  </header>

  {% if products %}
  <div class="row" style="background-color: #E8A75D; overflow: auto;">

    {% for product in products %}
    <div class="col-sm-4 d-flex justify-content-center mb-5 mt-5">
      <div class="card " style="height:450px; width:350px; background-color:#345A61">
        <div class="nutrimage">
          <img src="/static/finder/img/nutriscore-{{ product.nutrition_grade}}.svg"
            style="margin-bottom:1rem;max-width:100%"><br>
        </div>

        <div class="my-auto">
          <div class="text-center">
            <img class="mx-auto" style="width:auto; height:auto; max-width:250px; max-height:250px; "
              src="{{ product.picture }}">
          </div>
          <div class="card-body text-center">
            <h4 class="card-title" style="color:white">{{product.real_name}}</h4>
            <hr class="divider1 my-1" />
            <h4 class="card-title" style="color:white">"{{product.real_brand}}"</h4>
          </div>
        </div>

        <div class="savelink">
          <a href="{% url 'finder:detail' product.id %}" class="btn btn-primary"
            style="margin-top:1rem;max-width:100%">Selectionnez</a>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>

<div>
  {% if paginate %}
  <div style="background-color: #E8A75D; overflow: auto; ">
    <div class="clearfix"></div>
    <nav aria-label="">
      <ul class="pager mb-3">
        {% if products.has_previous %}
        <span><a href="?query={{query}}&page={{ products.previous_page_number }}">Previous</a></span>
        {% endif %}
        <span class="current" style='color:white;'>
          Page {{ products.number }} de {{ products.paginator.num_pages }}
        </span>
        {% if products.has_next %}
        <span><a href="?query={{query}}&page={{ products.next_page_number }}">Next</a></span>
        {% endif %}
  </div>
  </nav>
  {% endif %}
</div>

{% else %}
<div class='container-fluid' style='background-color:#E8A75D; overflow: auto;'>
  <hr>
  <div class='w-75 mx-auto  row d-flex justify-content-around mb-3'>
    <h3 class="intro-text text-center account_items" style="color: beige;">On n'a pas de {{ query }}, mais on a Léguman!
    </h3>
  </div>
  <hr>
  <div class="w-75  mx-auto container-fluid mb-3" style='background-color: transparent;'>
    <div class='row d-flex justify-content-center'>
      <iframe width="732" height="600" src="https://www.youtube.com/embed/oqMUCck2TLw" frameborder="0"
        allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    </div>
  </div>
</div>
{% endif %}

{% endblock %}

finder/templates/finder/substitute.html
{% extends 'finder/base.html' %}

{% block content %}
<div>
  <header class="nav_masthead" style="overflow: auto;">
    <div class="col-lg-12">
      <hr>
      {% if user.is_authenticated %}
      <h2 class="intro-text text-center" style="color: beige;">Enregistrez votre produit de substitution dans votre
        liste.</h2>
      <hr class="divider1 my-4" />
      {% else%}
      <h2 class="intro-text text-center" style="color: beige;">Si vous souhaitez enregistrer le produit dans une liste,
        inscrivez vous!</h2>
      <hr class="divider1 my-4" />
      {% endif %}
      <hr>
    </div>
  </header>

  <div class="row" style="background-color: #E8A75D;">

    {% for sub_product in products %}
    <div class="col-sm-4 d-flex justify-content-center mb-5 mt-5">
      <div class="card " style="height:450px; width:350px; background-color:#345A61">
        <div class="nutrimage">
          <img src="/static/finder/img/nutriscore-{{ sub_product.nutrition_grade}}.svg"
            style="margin-bottom:1rem;max-width:100%"><br>
        </div>
        <div class="my-auto">
          <div class="text-center">
            <img class="mx-auto" style="width:auto; height:auto; max-width:250px; max-height:250px; "
              src="{{ sub_product.picture }}">
          </div>
          <div class="card-body text-center">
            <h4 class="card-title" style="color:white">{{sub_product.real_name}}</h4>
            <hr class="divider1 my-1" />
            <h4 class="card-title" style="color:white">"{{sub_product.real_brand}}"</h4>
          </div>
        </div>

        <div class=" container-fluid card-footer border-top-0">
          <div class="row justify-content-end mx-2">
            {% if user.is_authenticated %}
            <a href="{% url 'finder:save' product.id sub_product.id %}" class='btn-top' role="button"><i
                class="top_1 fas fa-save"></i></a>
            <a href="{% url 'finder:detail' sub_product.id %}" class=" savedblink btn btn-primary bl-1"
              style="margin-top:1rem;max-width:100%">Fiche produit</a>
            {% else %}
            <a href="{% url 'finder:detail' sub_product.id %}" class=" savedblinknologged btn btn-primary bl-1"
              style="margin-top:1rem;max-width:100%">Fiche produit</a>
            {% endif %}
          </div>
        </div>
      </div>
    </div>

    {% endfor %}
  </div>
</div>

<div style="background-color: #E8A75D; overflow: auto; ">
  <div class="clearfix"></div>
  <nav aria-label="">
    <ul class="pager mb-3">
      {% if products.has_previous %}
      <span><a href="?query={{query}}&page={{ products.previous_page_number }}">Previous</a></span>
      {% endif %}
      <span class="current" style='color:white;'>
        Page {{ products.number }} de {{ products.paginator.num_pages }}
      </span>
      {% if products.has_next %}
      <span><a href="?query={{query}}&page={{ products.next_page_number }}">Next</a></span>
      {% endif %}
    </ul>
  </nav>
</div>

{% endblock %}

register/templates/register/register.html
{% extends "finder/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<header class="masthead">

    <div class="col-lg-12">
        <hr>        
        <h2 class="intro-text text-center" style="color: beige;">S'inscrire</h2>
        <hr class="divider1 my-4"/>
        <hr>
        <hr>            
    </div>


<div class="col-lg-4 mx-auto">
    <div class="crispy p-3 mx-auto" style="background-color: rgba(255, 255, 255, 0.65);">
        <form method="POST" class='form-group'>
            <div class='crispy'>
            {% csrf_token %}
            {{form|crispy}}
            <button type="submit" class='btn btn-sucess'>Rejoindre</button>
            </div>       
        </form>
    </div>
</div>

</header>
{% endblock %}